# Количество периферийных устройств, подключаемых к донглу
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_BT_BAS=y
CONFIG_ZMK_DISPLAY=y
# Увеличиваем максимальное количество одновременных BLE-подключений
# (2 половинки + 5 профилей для переключения между компьютерами)
# Включение дисплея ST7789 через модуль dongle_display
CONFIG_ZMK_DONGLE_DISPLAY_ST7789=y

# Пины подключения (согласно вашей распайке)
CONFIG_ZMK_DONGLE_DISPLAY_CS_PIN=1.06
CONFIG_ZMK_DONGLE_DISPLAY_DC_PIN=1.04
CONFIG_ZMK_DONGLE_DISPLAY_RST_PIN=0.11
CONFIG_ZMK_DONGLE_DISPLAY_BL_PIN=0.10
CONFIG_ZMK_DONGLE_DISPLAY_SPI_BUS=3
CONFIG_ZMK_DONGLE_DISPLAY_SPI_FREQUENCY=20000000

# Настройки цвета
CONFIG_LV_COLOR_DEPTH_16=y
CONFIG_LV_COLOR_16_SWAP=y