

CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y




# Основные настройки Bluetooth для донгла
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_BT_MAX_CONN=3
CONFIG_BT_MAX_PAIRED=3

# Настройки дисплея для версии v0.3
CONFIG_ZMK_DISPLAY=y
CONFIG_SPI=y
CONFIG_ST7789V=y

# Работа с цветом и памятью (ОБЯЗАТЕЛЬНО)
CONFIG_LV_Z_BITS_PER_PIXEL=16
CONFIG_LV_COLOR_DEPTH_16=y
CONFIG_LV_Z_VDB_SIZE=10

# Отключаем конфликтующий I2C
CONFIG_I2C=n
CONFIG_SSD1306=n

# Отключаем строгость Kconfig, если версия позволяет
CONFIG_ZMK_KCONFIG_STRICT=n
