CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_BT_BAS=y
CONFIG_ZMK_DISPLAY=y
CONFIG_MIPI_DBI=y
CONFIG_LV_COLOR_DEPTH_16=y
CONFIG_LV_COLOR_16_SWAP=y

# Отключаем драйвер старого дисплея
CONFIG_SSD1306=n

# Отключаем I2C полностью, так как он конфликтует с SPI0
CONFIG_I2C=n

# Убеждаемся, что SPI и MIPI включены для нового экрана
CONFIG_SPI=y

CONFIG_ST7789V=y

# Этот параметр включает именно кастомные виджеты этого модуля
CONFIG_ZMK_DONGLE_SCREEN_CUSTOM_WIDGETS=y
# --- Настройки памяти для цветного экрана (КРИТИЧНО) ---
CONFIG_LV_Z_BITS_PER_PIXEL=16
CONFIG_LV_Z_VDB_SIZE=10
# Удалите CONFIG_LV_COLOR_16_SWAP=y, если цвета будут странными (у ST7789 это часто не нужно)

# --- Экономия памяти (RAM) ---
# На nRF52840 (Nice!Nano) очень мало памяти для BLE + LVGL
CONFIG_BT_MAX_CONN=2
CONFIG_BT_MAX_PAIRED=2