# Количество периферийных устройств, подключаемых к донглу
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DONGLE_DISPLAY_BONGO_CAT=n
CONFIG_LOG=y
CONFIG_I2C_LOG_LEVEL_DBG=y
CONFIG_SSD1306_LOG_LEVEL_DBG=y
CONFIG_DISPLAY_LOG_LEVEL_DBG=y
# Увеличиваем максимальное количество одновременных BLE-подключений
# (2 половинки + 5 профилей для переключения между компьютерами)
CONFIG_BT_MAX_CONN=7
CONFIG_BT_MAX_PAIRED=7
